import type { Request, Response } from "express";
import { externalFetch } from "./http-client";
import { findCompetitorBySourceKey, getCompetitorSettingsByTaskUid, insertCompetitor, updateCompetitor, updateCompetitorFetch } from "./db";
import { sdk } from "./_core/sdk";

type GithubRepo = { id?: number; full_name?: string; html_url?: string; description?: string | null; stargazers_count?: number; forks_count?: number; open_issues_count?: number; language?: string | null; updated_at?: string };
export function competitorThreatScore(repo: Pick<GithubRepo, "stargazers_count" | "forks_count" | "open_issues_count">) { return Math.max(0, Math.min(100, Math.round(Math.log10((repo.stargazers_count ?? 0) + 1) * 22 + Math.log10((repo.forks_count ?? 0) + 1) * 10 + Math.min(repo.open_issues_count ?? 0, 50) * 0.25))); }
export async function fetchGithubCompetitors(query: string, now = new Date()) { const since = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10); const url = new URL("https://api.github.com/search/repositories"); url.searchParams.set("q", `${query} created:>${since}`); url.searchParams.set("sort", "stars"); url.searchParams.set("order", "desc"); url.searchParams.set("per_page", "25"); const response = await externalFetch(url.toString(), { headers: { Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "personal-ai-venture-os" } }); if (!response.ok) throw new Error(`GitHub competitors source failed (${response.status})`); const payload = await response.json() as { items?: GithubRepo[] }; return (payload.items ?? []).filter((repo): repo is GithubRepo & { id: number; full_name: string; html_url: string } => Boolean(repo.id && repo.full_name && repo.html_url)); }
export async function refreshCompetitorsForUser(userId: number, query: string) { const repos = await fetchGithubCompetitors(query); let inserted = 0; let updated = 0; for (const repo of repos) { const data = { sourceKey: `github:${repo.id}`, source: "github", name: repo.full_name, category: repo.language || "Open Source", url: repo.html_url, threatLevel: competitorThreatScore(repo), lastSeenAt: new Date(repo.updated_at || Date.now()), notes: `${repo.description?.trim() || "GitHub competitor repository"} · ${repo.stargazers_count ?? 0} stars · ${repo.forks_count ?? 0} forks`, status: "watching" }; const existing = await findCompetitorBySourceKey(userId, data.sourceKey); if (existing) { await updateCompetitor(userId, existing.id, data); updated += 1; } else { await insertCompetitor({ userId, ...data }); inserted += 1; } } await updateCompetitorFetch(userId, new Date()); return { fetched: repos.length, inserted, updated, source: "github" }; }
export async function competitorRefreshHandler(req: Request, res: Response) { try { const user = await sdk.authenticateRequest(req); if (!user.isCron || !user.taskUid) return res.status(403).json({ error: "cron-only" }); const settings = await getCompetitorSettingsByTaskUid(user.taskUid); if (!settings) return res.json({ ok: true, skipped: "orphan" }); if (!settings.enabled) return res.json({ ok: true, skipped: "disabled" }); if (settings.lastFetchedAt && Date.now() - new Date(settings.lastFetchedAt).getTime() < settings.refreshMinutes * 60_000) return res.json({ ok: true, skipped: "not-due", nextAfterMinutes: settings.refreshMinutes }); const result = await refreshCompetitorsForUser(settings.userId, settings.query); return res.json({ ok: true, ...result, fetchedAt: new Date().toISOString() }); } catch (error) { const message = error instanceof Error ? error.message : String(error); const status = /session|cron|forbidden|unauthorized/i.test(message) ? 403 : 500; return res.status(status).json({ error: status === 403 ? "forbidden" : "competitors-refresh-failed", timestamp: new Date().toISOString() }); } }
